# Site settings
title:       Luiz Picolo
email:       luizpicolo@gmail.com
baseurl:     ""
url:         "http://luizpicolo.com.br"
date_format: "%d de %b de %Y"

# Google services
google_verification:
# Use either direct GA implementation or set up GTM account
# - using both will skew your data (leave blank to not use at all)
google_analytics:
google_tag_manager:
# Bing services
bing_verification:

# Optional features
animated:             false
show_related_posts:   false
show_post_footers:    false
show_social_icons:    true
ajaxify_contact_form: true
enable_mathjax: true
extended_fonts: true
enable_anchorjs: true

# Disqus post comments
disqus_shortname: luizpicolo

# Facebook Comments plugin
facebook_comments:
facebook_appid:
facebook_comments_number: 10

# Social icons
github_username: luizpicolo
bitbucket_username: luizpicolo
stackoverflow_id:
twitter_username: luizpicolo_
skype_username: luiz.picolo
steam_nickname:
google_plus_id:
linkedin_username: luizpicolo
angellist_username:
medium_id:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: false
share_facebook: true
share_twitter: true
share_googleplus: true
share_linkedin: false
share_digg: true
share_tumblr: true
share_reddit: true
share_stumbleupon: true
share_hackernews: true

text:
  pagination:
    newer:
    older:
  share_buttons:
    text:         'Compartilhe esta postagem!'
    facebook:     'Compartilhar no Facebook'
    twitter:      'Compartilhar no Twitter'
    googleplus:   'Compartilhar no Google+'
    linkedin:     'Compartilhar no LinkedIn'
    digg:         'Compartilhar no Digg'
    tumblr:       'Compartilhar no Tumblr'
    reddit:       'Compartilhar no Reddit'
    stumbleupon:  'Compartilhar no StumbleUpon'
    hackernews:   'Compartilhar no Hacker News'
  post:
    updated:        'Atualizado'
    minute_read:    'minutos de leitura'
    related_posts:  'Postagens relacionadas'
  index:
    coming_soon: 'Coming soon...'
  contact:
    email:    'Email'
    content:  'O que você gostaria de dizer?'
    subject:  'Novo envio!'
    submit:   'Diga olá'
    ajax:
      sending:  'enviando..'
      sent:     'Mensagem enviada!'
      error:    'Erro!'
  thanks: 'Obrigado por me contactar. Entrarei em contato assim que possível.'
  og_locale: 'pt_BR'

# Build settings
locales: pt
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
redcarpet:
  extensions: ["smart", "no_intra_emphasis", "tables", "autolink", "strikethrough", "with_toc_data"]
permalink: /:year/:month/:day/:slug/
excerpt_separator: <!--more-->
paginate: 100
sass:
  compressed: true
gems:
  - jekyll-paginate
  - jekyll-sitemap
  # https://github.com/jekyll/jekyll/issues/2938
exclude: [vendor]
